### ISSUE TITLE
최근 스타벅스 WIFI 이용 방식 변경(?)에 따라 Captive Network Assistant 동의 click 필요함.

### ISSUE THREAD

**Issue by tkhwang** [taggon/coffeefy#3]
안녕하세요...

coffeefy 잘 쓰고 있는 유저입니다.

최근에 스타벅스 WIFI 이용 방식(?)이 변경 되었는지.... 
Captive Network Assistant 창에서 동의 click 해야만 스타벅스 WIFI 연결 가능합니다.

따라서, 기본 coffeey 사용 환경에는 `KT_starbucks` WIFI 잡아도 인터넷 되지 않네요.

```
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -boolean true
```

Captive Network Assistant `enable` 한 후에 창에서 동의 해주면 됩니다.
coffeey app issue 는 아니지만 혹시나 남깁니다. :)

**Comment by taggon** [comment]
[v1.3.1](https://github.com/taggon/coffeefy/releases/tag/v1.3.1)에서 수정되었습니다. 변경된 접속 방식을 지원합니다. 😄

**Comment by tkhwang** [comment]
우아.. 바로 수정해주시고 고맙습니다.
스벅 들리게 되면 바로 테스트 해볼께요.

고맙습니다. 👍
